/**
 * WeeChat Relay Bridge Server
 *
 * This server emulates a WeeChat Relay server, allowing clients like Lith
 * to connect to nexuslounge backend (which connects to erssi fe-web).
 *
 * Architecture:
 * - Lith client connects via WebSocket/TCP
 * - This bridge translates WeeChat Relay protocol <-> erssi fe-web protocol
 * - Uses existing IrssiClient for actual IRC connection
 *
 * Protocol flow:
 * 1. Client connects
 * 2. Client sends: handshake (optional, for auth negotiation)
 * 3. Client sends: init (authentication)
 * 4. Server sends: initial state (buffers, lines, nicklist)
 * 5. Client sends: sync (subscribe to updates)
 * 6. Bidirectional: messages, commands, updates
 */

import {Server as NetServer, Socket as NetSocket} from "net";
import * as tls from "tls";
import * as https from "https";
import * as fs from "fs";
import WebSocket, {WebSocketServer} from "ws";
import {EventEmitter} from "events";
import log from "../log.js";
import chalk from "chalk";
import {WeeChatMessage, WeeChatParser} from "./weechatProtocol.js";
import {WeeChatRelayClient} from "./weechatRelayClient.js";

export interface WeeChatRelayServerConfig {
    // Port (single port per user)
    port: number;
    host?: string;

    // Protocol
    protocol: "tcp" | "ws"; // TCP or WebSocket
    wsPath?: string; // WebSocket path (default: /weechat)

    // TLS/SSL
    tls: boolean;
    certPath?: string; // Path to certificate file
    keyPath?: string; // Path to private key file

    // Authentication
    password?: string;
    passwordHashAlgo?: string[];
    passwordHashIterations?: number;

    // Compression
    compression?: boolean;
}

/**
 * WeeChat Relay Bridge Server
 */
export class WeeChatRelayServer extends EventEmitter {
    private config: WeeChatRelayServerConfig;
    private server: NetServer | tls.Server | https.Server | null = null;
    private wsServer: WebSocketServer | null = null;
    private clients: Map<string, WeeChatRelayClient> = new Map();
    private clientIdCounter = 0;

    constructor(config: WeeChatRelayServerConfig) {
        super();
        this.config = {
            host: "0.0.0.0",
            wsPath: "/weechat",
            password: "",
            passwordHashAlgo: ["plain", "sha256", "sha512", "pbkdf2+sha256", "pbkdf2+sha512"],
            passwordHashIterations: 100000,
            compression: true,
            ...config,
        };

        log.info(
            `${chalk.green("[WeeChat Relay]")} Creating WeeChatRelayServer: ` +
                `protocol=${this.config.protocol}, port=${this.config.port}, tls=${this.config.tls}`
        );
    }

    /**
     * Start the server (TCP or WebSocket, with or without TLS)
     */
    async start(): Promise<void> {
        if (this.config.protocol === "tcp") {
            await this.startTcpServer();
        } else if (this.config.protocol === "ws") {
            await this.startWebSocketServer();
        } else {
            throw new Error(`Unknown protocol: ${this.config.protocol}`);
        }

        const tlsStr = this.config.tls ? "TLS" : "plain";
        log.info(
            `${chalk.green(
                "[WeeChat Relay]"
            )} ✅ Started ${this.config.protocol.toUpperCase()} server (${tlsStr}) on ${
                this.config.host
            }:${this.config.port}`
        );
    }

    /**
     * Start TCP server (with or without TLS)
     */
    private async startTcpServer(): Promise<void> {
        return new Promise((resolve, reject) => {
            if (this.config.tls) {
                // TLS TCP server
                if (!this.config.certPath || !this.config.keyPath) {
                    reject(new Error("TLS enabled but certPath/keyPath not provided"));
                    return;
                }

                // certPath should already contain the full chain (server cert + CA cert)
                // generated by sslCertGenerator.ts
                const options: tls.TlsOptions = {
                    key: fs.readFileSync(this.config.keyPath),
                    cert: fs.readFileSync(this.config.certPath), // Full chain!
                };

                log.info(
                    `${chalk.cyan("[WeeChat Relay]")} Using certificate: ${this.config.certPath}`
                );

                this.server = tls.createServer(options, (socket: tls.TLSSocket) => {
                    // Log TLS errors (handshake failures, etc.)
                    socket.on("error", (err) => {
                        log.error(
                            `${chalk.red("[WeeChat Relay]")} TLS socket error: ${err.message}`
                        );
                        log.error(`${chalk.red("[WeeChat Relay]")} TLS error stack: ${err.stack}`);
                    });

                    socket.on("secureConnect", () => {
                        log.info(`${chalk.green("[WeeChat Relay]")} TLS handshake successful`);
                    });

                    this.handleTcpConnection(socket);
                });

                log.info(`${chalk.cyan("[WeeChat Relay]")} Starting TLS TCP server...`);
            } else {
                // Plain TCP server
                this.server = new NetServer();
                this.server.on("connection", (socket: NetSocket) => {
                    this.handleTcpConnection(socket);
                });

                log.info(`${chalk.cyan("[WeeChat Relay]")} Starting plain TCP server...`);
            }

            this.server.on("error", (err) => {
                log.error(`${chalk.red("[WeeChat Relay]")} TCP server error: ${err}`);
                reject(err);
            });

            this.server.listen(this.config.port, this.config.host, () => {
                log.info(
                    `${chalk.green("[WeeChat Relay]")} TCP server listening on ${
                        this.config.host
                    }:${this.config.port}`
                );
                resolve();
            });
        });
    }

    /**
     * Start WebSocket server (with or without TLS)
     */
    private async startWebSocketServer(): Promise<void> {
        return new Promise((resolve, reject) => {
            if (this.config.tls) {
                // WSS (WebSocket Secure)
                if (!this.config.certPath || !this.config.keyPath) {
                    reject(new Error("TLS enabled but certPath/keyPath not provided"));
                    return;
                }

                // certPath should already contain the full chain (server cert + CA cert)
                const httpsServer = https.createServer({
                    key: fs.readFileSync(this.config.keyPath),
                    cert: fs.readFileSync(this.config.certPath), // Full chain!
                });

                log.info(
                    `${chalk.cyan("[WeeChat Relay]")} Using certificate for WSS: ${
                        this.config.certPath
                    }`
                );

                this.wsServer = new WebSocketServer({
                    server: httpsServer,
                    path: this.config.wsPath,
                });

                httpsServer.listen(this.config.port, this.config.host, () => {
                    log.info(
                        `${chalk.green("[WeeChat Relay]")} WSS server listening on ${
                            this.config.host
                        }:${this.config.port}${this.config.wsPath}`
                    );
                    resolve();
                });

                httpsServer.on("error", (err) => {
                    log.error(`${chalk.red("[WeeChat Relay]")} HTTPS server error: ${err}`);
                    reject(err);
                });

                this.server = httpsServer;
                log.info(
                    `${chalk.cyan("[WeeChat Relay]")} Starting WSS (WebSocket Secure) server...`
                );
            } else {
                // Plain WebSocket
                this.wsServer = new WebSocketServer({
                    host: this.config.host,
                    port: this.config.port,
                    path: this.config.wsPath,
                });

                this.wsServer.on("listening", () => {
                    log.info(
                        `${chalk.green("[WeeChat Relay]")} WebSocket server listening on ${
                            this.config.host
                        }:${this.config.port}${this.config.wsPath}`
                    );
                    resolve();
                });

                log.info(`${chalk.cyan("[WeeChat Relay]")} Starting plain WebSocket server...`);
            }

            this.wsServer.on("connection", (ws: WebSocket) => {
                this.handleWebSocketConnection(ws);
            });

            this.wsServer.on("error", (err) => {
                log.error(`${chalk.red("[WeeChat Relay]")} WebSocket server error: ${err}`);
                reject(err);
            });
        });
    }

    /**
     * Handle TCP connection
     */
    private handleTcpConnection(socket: NetSocket): void {
        const clientId = `tcp-${this.clientIdCounter++}`;
        const remoteAddr = `${socket.remoteAddress}:${socket.remotePort}`;

        // Log TLS info if this is a TLS socket
        if ((socket as any).encrypted) {
            const tlsSocket = socket as tls.TLSSocket;
            log.info(
                `${chalk.green(
                    "[WeeChat Relay]"
                )} New TLS connection: ${clientId} from ${remoteAddr}`
            );
            log.info(
                `${chalk.cyan(
                    "[WeeChat Relay]"
                )} TLS version: ${tlsSocket.getProtocol()}, cipher: ${tlsSocket.getCipher()?.name}`
            );
        } else {
            log.info(
                `${chalk.green(
                    "[WeeChat Relay Bridge]"
                )} New TCP connection: ${clientId} from ${remoteAddr}`
            );
        }

        const client = new WeeChatRelayClient(clientId, socket, this.config);
        this.clients.set(clientId, client);

        // Forward events
        client.on("authenticated", (user) => {
            this.emit("client:authenticated", clientId, user);

            // Emit "clients:first" when first client connects (for lazy emit optimization)
            if (this.clients.size === 1) {
                this.emit("clients:first");
                log.info(
                    `${chalk.green(
                        "[WeeChat Relay]"
                    )} First client connected - starting event forwarding`
                );
            }
        });

        client.on("command", (command, args) => {
            this.emit("client:command", clientId, command, args);
        });

        client.on("close", () => {
            log.info(
                `${chalk.yellow("[WeeChat Relay Bridge]")} TCP connection closed: ${clientId}`
            );
            this.clients.delete(clientId);
            this.emit("client:close", clientId);

            // Emit "clients:none" when last client disconnects (for lazy emit optimization)
            if (this.clients.size === 0) {
                this.emit("clients:none");
                log.info(
                    `${chalk.yellow(
                        "[WeeChat Relay]"
                    )} Last client disconnected - stopping event forwarding`
                );
            }
        });

        client.on("error", (err) => {
            log.error(
                `${chalk.red("[WeeChat Relay Bridge]")} TCP client error: ${clientId} - ${err}`
            );
        });
    }

    /**
     * Handle WebSocket connection
     */
    private handleWebSocketConnection(ws: WebSocket): void {
        const clientId = `ws-${this.clientIdCounter++}`;

        log.info(`${chalk.green("[WeeChat Relay Bridge]")} New WebSocket connection: ${clientId}`);

        const client = new WeeChatRelayClient(clientId, ws, this.config);
        this.clients.set(clientId, client);

        // Forward events
        client.on("authenticated", (user) => {
            this.emit("client:authenticated", clientId, user);

            // Emit "clients:first" when first client connects (for lazy emit optimization)
            if (this.clients.size === 1) {
                this.emit("clients:first");
                log.info(
                    `${chalk.green(
                        "[WeeChat Relay]"
                    )} First client connected - starting event forwarding`
                );
            }
        });

        client.on("command", (command, args) => {
            this.emit("client:command", clientId, command, args);
        });

        client.on("close", () => {
            log.info(
                `${chalk.yellow("[WeeChat Relay Bridge]")} WebSocket connection closed: ${clientId}`
            );
            this.clients.delete(clientId);
            this.emit("client:close", clientId);

            // Emit "clients:none" when last client disconnects (for lazy emit optimization)
            if (this.clients.size === 0) {
                this.emit("clients:none");
                log.info(
                    `${chalk.yellow(
                        "[WeeChat Relay]"
                    )} Last client disconnected - stopping event forwarding`
                );
            }
        });

        client.on("error", (err) => {
            log.error(
                `${chalk.red(
                    "[WeeChat Relay Bridge]"
                )} WebSocket client error: ${clientId} - ${err}`
            );
        });
    }

    /**
     * Get client by ID
     */
    getClient(clientId: string): WeeChatRelayClient | undefined {
        return this.clients.get(clientId);
    }

    /**
     * Get all clients
     */
    getClients(): WeeChatRelayClient[] {
        return Array.from(this.clients.values());
    }

    /**
     * Check if any clients are connected
     * Used to optimize event forwarding - don't emit when no one is listening
     */
    hasClients(): boolean {
        return this.clients.size > 0;
    }

    /**
     * Get number of connected clients
     * Used for metrics and monitoring
     */
    getConnectionCount(): number {
        return this.clients.size;
    }

    /**
     * Stop the server
     */
    async stop(): Promise<void> {
        log.info(`${chalk.cyan("[WeeChat Relay]")} Stopping server...`);

        // First, try to close all clients gracefully
        for (const client of this.clients.values()) {
            try {
                client.close();
            } catch (err) {
                log.warn(`${chalk.yellow("[WeeChat Relay]")} Error closing client:`, err);
            }
        }

        // Give clients a brief moment to close gracefully, then force-close anything remaining
        await new Promise<void>((resolve) => {
            setTimeout(() => {
                for (const client of this.clients.values()) {
                    try {
                        client.forceClose();
                    } catch (err) {
                        log.warn(`${chalk.yellow("[WeeChat Relay]")} Error force-closing client:`, err);
                    }
                }
                this.clients.clear();
                resolve();
            }, 300); // 300ms grace period is enough to flush pending data
        });

        const waitForClose = async (
            closeFn: (callback: () => void) => void,
            timeoutMs: number,
            onTimeout: () => void
        ): Promise<"ok" | "timeout"> => {
            return new Promise<"ok" | "timeout">((resolve) => {
                let finished = false;
                let timer: NodeJS.Timeout;

                const finish = (result: "ok" | "timeout") => {
                    if (finished) {
                        return;
                    }
                    finished = true;
                    clearTimeout(timer);
                    resolve(result);
                };

                timer = setTimeout(() => {
                    onTimeout();
                    finish("timeout");
                }, timeoutMs);

                try {
                    closeFn(() => finish("ok"));
                } catch (err) {
                    log.warn(`${chalk.yellow("[WeeChat Relay]")} Error while closing server:`, err);
                    finish("ok");
                }
            });
        };

        // Close main server (TCP/TLS or HTTPS for WSS) with timeout
        if (this.server) {
            const serverToClose = this.server;
            const serverCloseResult = await waitForClose(
                (callback) => serverToClose.close(callback),
                1000,
                () => {
                    log.warn(
                        `${chalk.yellow("[WeeChat Relay]")} Server close timeout - forcing shutdown`
                    );
                    try {
                        serverToClose.close();
                    } catch (err) {
                        log.warn(
                            `${chalk.yellow("[WeeChat Relay]")} Error during forced server close:`,
                            err
                        );
                    }
                }
            );

            if (serverCloseResult === "timeout") {
                log.warn(
                    `${chalk.yellow("[WeeChat Relay]")} Server did not close cleanly - continuing with shutdown`
                );
            }

            this.server = null;
        }

        // Close WebSocket server with timeout
        if (this.wsServer) {
            const wsServerToClose = this.wsServer;
            const wsCloseResult = await waitForClose(
                (callback) => wsServerToClose.close(callback),
                1000,
                () => {
                    log.warn(
                        `${chalk.yellow(
                            "[WeeChat Relay]"
                        )} WebSocket server close timeout - forcing shutdown`
                    );
                    try {
                        for (const ws of wsServerToClose.clients) {
                            ws.terminate();
                        }
                    } catch (err) {
                        log.warn(
                            `${chalk.yellow("[WeeChat Relay]")} Error during forced WebSocket server close:`,
                            err
                        );
                    }
                }
            );

            if (wsCloseResult === "timeout") {
                log.warn(
                    `${chalk.yellow(
                        "[WeeChat Relay]"
                    )} WebSocket server did not close cleanly - continuing with shutdown`
                );
            }

            this.wsServer = null;
        }

        log.info(`${chalk.yellow("[WeeChat Relay]")} Server stopped`);
    }

}
